stages:
  - publish

variables:
  GRADLE_OPTS: "-Dorg.gradle.user.home=$CI_PROJECT_DIR/.gradle"
  GIT_DEPTH: 0

default:
  image: gradle:9.6.1-jdk21
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .gradle/wrapper
      - .gradle/caches
  before_script:
    - chmod +x ./gradlew

publish:
  stage: publish
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - ./gradlew modrinth curseforge --no-daemon

